apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- kube-prometheus-stack-version_65.x/alertmanagerconfigs.yaml
- kube-prometheus-stack-version_65.x/podmonitors.yaml
- kube-prometheus-stack-version_65.x/prometheusagents.yaml
- kube-prometheus-stack-version_65.x/prometheusrules.yaml
- kube-prometheus-stack-version_65.x/servicemonitors.yaml
- kube-prometheus-stack-version_65.x/alertmanagers.yaml
- kube-prometheus-stack-version_65.x/probes.yaml
- kube-prometheus-stack-version_65.x/prometheuses.yaml
- kube-prometheus-stack-version_65.x/scrapeconfigs.yaml
- kube-prometheus-stack-version_65.x/thanosrulers.yaml
patches:
- patch: |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: alertmanagerconfigs.monitoring.coreos.com
      annotations: {}
- patch: |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: alertmanagers.monitoring.coreos.com
      annotations: {}
- patch: |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: prometheusagents.monitoring.coreos.com
      annotations: {}
- patch: |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: prometheuses.monitoring.coreos.com
      annotations: {}
- patch: |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: scrapeconfigs.monitoring.coreos.com
      annotations: {}
- patch: |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: thanosrulers.monitoring.coreos.com
      annotations: {}
